#!/usr/bin/env python

Import("env")

if "GLES2_GLSL" in env["BUILDERS"]:
    # find all include files
    gl_include_files = [str(f) for f in Glob("*_inc.glsl")]

    # find all shader code(all glsl files excluding our include files)
    glsl_files = [str(f) for f in Glob("*.glsl") if str(f) not in gl_include_files]

    # make sure we recompile shaders if include files change
    env.Depends([f + ".gen.h" for f in glsl_files], gl_include_files + ["#gles_builders.py"])

    # TODO: this is an ugly ugly hack
    # I only use this because scons just refuses to run the builder and I can't giure out why
    import os, sys

    sys.path.append("../../..")
    from gles_builders import build_gles2_headers
    
    build_gles2_headers(0, glsl_files, 0)

    for f in glsl_files:
        print(f)
        env.GLES2_GLSL(f)

SConscript("effects/SCsub")
